sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- 6
before_script:
- npm prune
- 'curl -Lo travis_after_all.py https://git.io/vLSON'
after_success:
- npm run coverage:upload
- python travis_after_all.py
- export $(cat .to_export_back)
- npm run semantic-release
